### PR TITLE
Update to 1.8.7

### PR DESCRIPTION
**Pull request by JamieSinn**
Add deploy too

### CODE REVIEW

**Comment by xxmicloxx** [comment]
Why is there a distributionManagement section?

**Comment by JamieSinn** [comment]
I pushed it to my maven repo due to it being quite a pain to have to add a local depend. 

I can give you a CI job too if needed.

**Comment by xxmicloxx** [comment]
The problem is that I currently don't have a public maven repo... Do you have a public one?

**Comment by JamieSinn** [comment]
Yes I do. As well as a Jenkins server

**Comment by xxmicloxx** [comment]
If you provide public builds (through maven) I'll leave the deploy part in. Also, please squash your commits.

**Comment by JamieSinn** [comment]
```
<dependency>
    <groupId>com.xxmicloxx</groupId>
    <artifactId>NoteBlockAPI</artifactId>
    <version>1.8.7</version>
</dependency>

        <repository>
            <id>sinndev-repo</id>
            <url>http://repo.sinndev.com/content/groups/public/</url>
        </repository>
```

**Comment by JamieSinn** [comment]
And I forgot I was on the master branch for those edits :p oops

**Pull request merged**
